[RDPF - 64] 회원탈퇴 useCase 작성
read-a-perfume/backend pull request #110
Opened 2023-07-22 08:52 UTC by kma952727

## What is this PR? 👀

delete "/v1/users" API 작성, 사용자는 api호출 시 회원탈퇴(soft delete)

탈퇴 성공 시 http status 202
탈퇴 실패 시 http status 401을 반환

- Issue ticket number: RDPF - 64

## Changes ✏️

1. perfume-api/src/main/java/io/perfume/api/auth/application/service/AuthenticationTokenService.java에 간단한 개선사항 TODO 작성
2. User Model에 softDelete() 메서드 작성

## Test checklist 🧪

- [ ]

2023-07-27 14:13 UTC, oliviarla requested changes
고생하셨습니다 ! 리뷰 달아보았어요
그리고 회원 탈퇴 용어를 leave vs delete 중에 leave로 선택하신 이유가 따로 있나요?

2023-07-27 14:13 UTC, oliviarla commented on perfume-api/src/main/java/io/perfume/api/user/application/exception/FailedLeaveException.java
> +public class FailedLeaveException extends CustomHttpException {
이름을 FailedToLeaveException 로 변경하는게 좋을 것 같습니다!

2023-07-27 14:13 UTC, oliviarla commented on perfume-api/src/main/java/io/perfume/api/user/application/service/SupportUserService.java
> -    @Transactional
여기는 왜 삭제되었나요?🧐

2023-07-27 14:13 UTC, oliviarla commented on perfume-api/src/main/java/io/perfume/api/user/adapter/in/http/UsersSupportController.java
> +    public ResponseEntity leaveUser(@RequestHeader(name = "Authorization") String accessToken) {
현재 access token이 헤더로 들어오고 있지 않습니다..!
그리고 @AuthenticationPrincipal로 SecurityContext 내의 UserPrincipal 구현체를 받아오는게 좋을 것 같아요!

2023-07-27 14:13 UTC, oliviarla commented on perfume-api/src/main/java/io/perfume/api/user/application/port/in/LeaveUserUseCase.java
> +    void leave(String accessToken);
accessToken 대신 user의 PK를 인자로 받도록 변경이 필요합니당!

2023-07-27 14:13 UTC, oliviarla commented on perfume-api/src/main/java/io/perfume/api/user/application/service/SupportUserService.java
> +            userRepository.save(user);
@dygma0 @Big-Cir97 @kma952727 
코딩 스타일에 관한 질문입니다.
저는 이 부분을 userRepository의 softDelete() 메소드 하나로 묶어서 처리하면 변경 감지로 처리할 수 있겠다 생각이 들었는데, DDD 를 따른다고 생각하면 이 방식도 괜찮아보이네요.

각자의 의견이 궁금합니다 🙌🏻

2023-07-28 23:53 UTC, kma952727 commented on perfume-api/src/main/java/io/perfume/api/user/application/exception/FailedLeaveException.java
> +public class FailedLeaveException extends CustomHttpException {
수정하겠습니다!

2023-07-29 01:50 UTC, kma952727 commented on perfume-api/src/main/java/io/perfume/api/user/application/service/SupportUserService.java
> -    @Transactional
정말 꼼꼼하시네요! 수정했습니다!

2023-07-29 02:21 UTC, kma952727 commented on perfume-api/src/main/java/io/perfume/api/user/application/service/SupportUserService.java
> +            userRepository.save(user);
Adapter에 delete 로직이 들어가면 현재 구현한 Adapter를 걷어냈을 때 삭제 동작이 사라지지 않는게 아닐까? 생각이 듭니다.
다른 분들 의견도 궁금합니다!

2023-07-31 07:31 UTC, merged